---
version: "2.4"
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_PASSWORD=p@ssword
      - MARIADB_DATABASE=akaunting
      - MARIADB_USER=akaunting
    ports:
      - "3306:3306"
    networks:
      - akaunting

  app:
    image: penguintech/akaunting
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mariadb
    networks:
      - akaunting
    healthcheck:
      test: ["CMD", "ansible-playbook", "entrypoint.yml", "--tag", "test"]
      interval: 5m
      timeout: 10s
      retries: 5
      start_period: 5s

networks:
  akaunting:
