run:
  user: ptg-user
app:
  title: "{{ lookup('ansible.builtin.env', 'APP_TILE') }}"
  link: "{{ lookup('env', 'APP_LINK') }}"

database:
  name: "{{ lookup('env', 'DATABASE_NAME') }}"
  user: "{{ lookup('env', 'DATABASE_USER') }}"
  password: "{{ lookup('env', 'DATABASE_PASSWORD') }}"
  host: "{{ lookup('env', 'DATABASE_HOST') }}"
  port: "{{ lookup('env', 'DATABASE_PORT') }}"

organization:
  name: "{{ lookup('env', 'ORGANIZATION_NAME') }}"
  country: "{{ lookup('env', 'ORGANIZATION_COUNTRY') }}"
  email: "{{ lookup('env', 'ORGANIZATION_EMAIL') }}"
  hostname: "{{ lookup('env', 'ORGANISATION_HOSTNAME') }}"

url: "{{ lookup('env', 'URL') }}"

ssl_key: "{{ lookup('env', 'SSL_KEY') }}"
ssl_cert: "{{ lookup('env', 'SSL_CERT') }}"

ports:
  - 80
  - 443